controller_manager:
  ros__parameters:
    update_rate: 15   # Frequenza di aggiornamento del controller_manager (Hz)

    # =========================
    # 📤 Joint State Broadcaster
    # =========================
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      # Pubblica tutte le interfacce di stato su /joint_states

    # =========================
    # 🚗 Controller di velocità Mecanum
    # =========================
    mecanum_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
      # Controller velocity per gruppo di giunti ruota

    # =========================
    # 📡 IMU Broadcaster
    # =========================
    imu_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster
      publish_rate: 15
      sensor_name: imu
      frame_id: imu_link
      topic_name: /data/imu

    # =========================
    # 🎯 Controller posizione servomotori pan/tilt
    # =========================
    pan_tilt_controller:
      type: position_controllers/JointGroupPositionController

    # =========================
    # 📡 Sonar Broadcaster (range)
    # =========================
    sonar_front_broadcaster:
      type: range_sensor_broadcaster/RangeSensorBroadcaster
    sonar_left_broadcaster:
      type: range_sensor_broadcaster/RangeSensorBroadcaster
    sonar_right_broadcaster:
      type: range_sensor_broadcaster/RangeSensorBroadcaster

# =========================
# ⚙️ Parametri runtime
# =========================

joint_state_broadcaster:
  ros__parameters: {}

mecanum_velocity_controller:
  ros__parameters:
    joints:
      - front_left_wheel_joint
      - front_right_wheel_joint
      - rear_left_wheel_joint
      - rear_right_wheel_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

imu_broadcaster:
  ros__parameters:
    sensor_name: imu         # Deve combaciare con export_state_interfaces ("imu")
    frame_id: imu_link
    publish_rate: 15
    topic_name: /data/imu

pan_tilt_controller:
  ros__parameters:
    joints:
      - pan_joint
      - tilt_joint

sonar_front_broadcaster:
  ros__parameters:
    sensor_name: sonar_front
    frame_id: sonar_front_link
    topic_name: /data/sonar_front
    field_of_view: 0.5
    min_range: 0.02
    max_range: 4.0

sonar_left_broadcaster:
  ros__parameters:
    sensor_name: sonar_left
    frame_id: sonar_left_link
    topic_name: /data/sonar_left
    field_of_view: 0.5
    min_range: 0.02
    max_range: 4.0

sonar_right_broadcaster:
  ros__parameters:
    sensor_name: sonar_right
    frame_id: sonar_right_link
    topic_name: /data/sonar_right
    field_of_view: 0.5
    min_range: 0.02
    max_range: 4.0