# =========================
# ⚙️ Configurazione del controller_manager
# =========================
controller_manager:
  ros__parameters:
    update_rate: 50   # Frequenza (in Hz) con cui il controller_manager aggiorna tutti i controller attivi.

    # =========================
    # 📤 Joint State Broadcaster
    # =========================
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      # Pubblica lo stato dei giunti (position, velocity, effort) sul topic /joint_states.
      # Utile per RViz, diagnosi e strumenti di visualizzazione.

    # =========================
    # 🚗 Controller di velocità per base Mecanum
    # =========================
    mecanum_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
      # Controller che accetta comandi di velocità per un gruppo di giunti.
      # Utilizzato per controllare le ruote della base Mecanum tramite messaggi Twist.

    # =========================
    # 📡 IMU Broadcaster
    # =========================
    imu_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster
      # Broadcaster standard che pubblica i dati del sensore IMU come messaggi sensor_msgs/Imu.

    # =========================
    # 📡 IR Sensor Broadcasters (standard ROS2)
    # =========================
    ir_front_left_broadcaster:
      type: range_sensor_broadcaster/RangeSensorBroadcaster
      # Broadcaster standard per il sensore IR frontale sinistro.

    ir_front_center_broadcaster:
      type: range_sensor_broadcaster/RangeSensorBroadcaster
      # Broadcaster standard per il sensore IR frontale centrale.

    ir_front_right_broadcaster:
      type: range_sensor_broadcaster/RangeSensorBroadcaster
      # Broadcaster standard per il sensore IR frontale destro.

# =========================
# ⚙️ Parametri specifici per ciascun controller
# =========================

joint_state_broadcaster:
  ros__parameters: {}
  # Nessun parametro aggiuntivo richiesto per il Joint State Broadcaster.

mecanum_velocity_controller:
  ros__parameters:
    joints:
      - front_left_wheel_joint     # Giunto della ruota anteriore sinistra
      - front_right_wheel_joint    # Giunto della ruota anteriore destra
      - rear_left_wheel_joint      # Giunto della ruota posteriore sinistra
      - rear_right_wheel_joint     # Giunto della ruota posteriore destra
    command_interfaces:
      - velocity                   # Interfaccia di comando: velocità
    state_interfaces:
      - position                   # Interfaccia di stato: posizione
      - velocity                   # Interfaccia di stato: velocità

imu_broadcaster:
  ros__parameters:
    sensor_name: imu               # Nome logico del sensore IMU (deve combaciare con quello esportato dall'hardware)
    frame_id: imu_link             # Frame di riferimento del sensore IMU (usato per trasformazioni TF)
    publish_rate: 50               # Frequenza di pubblicazione dei dati IMU (in Hz)
    topic_name: /data/imu          # Topic su cui pubblicare i dati IMU (sensor_msgs/Imu)

# =========================
# 📡 Parametri per ciascun IR Sensor Broadcaster
# =========================

ir_front_left_broadcaster:
  ros__parameters:
    sensor_name: ir_front_left         # Nome dell'interfaccia hardware esportata
    frame_id: ir_front_left_link       # Frame di riferimento per il sensore IR sinistro
    radiation_type: 1                  # Tipo di radiazione: 1 = INFRARED
    field_of_view: 0.5236              # Angolo di apertura del sensore [rad] ≈ ±15°
    min_range: 0.04                    # Distanza minima misurabile [m]
    max_range: 0.30                    # Distanza massima misurabile [m]
    publish_rate: 50                   # Frequenza di pubblicazione [Hz]

ir_front_center_broadcaster:
  ros__parameters:
    sensor_name: ir_front_center
    frame_id: ir_front_center_link
    radiation_type: 1
    field_of_view: 0.5236              # [rad] ±15°
    min_range: 0.04
    max_range: 0.30
    publish_rate: 50

ir_front_right_broadcaster:
  ros__parameters:
    sensor_name: ir_front_right
    frame_id: ir_front_right_link
    radiation_type: 1
    field_of_view: 0.5236              # [rad] ±15°
    min_range: 0.04
    max_range: 0.30
    publish_rate: 50
